name: Ubuntu Python Tests
'on': push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.10'
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: 'sudo apt-get update

        sudo apt-get install -y libportaudio2

        '
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install pytest

        pip install .'
    - name: Run tests
      env:
        AIDER_ANALYTICS: false
      run: pytest --deselect "tests/basic/test_commands.py::TestCommands::test_cmd_read_only_with_image_file" --deselect "tests/basic/test_commands.py::TestCommands::test_cmd_tokens_output" --deselect "tests/basic/test_models.py::TestModels::test_max_context_tokens" --deselect "tests/basic/test_repomap.py::TestRepoMapAllLanguages::test_language_csharp"
